# 特徴量リストの定義
FEATURE:
  "FEATURE_LIST":
    [
    # "land_toshi",
    # "land_chisei", 
    # "land_road_cond",
    # "reform_exterior_date", 
    # 'total_floor_area',
    # 'building_area',
    # 'building_structure',
    # 'building_land_area',
    # 'land_area_all',
    # 'land_youto',
    # 'management_form',
    # 'room_count',
    'unit_area',
    'floor_plan_code',
    # 'reform_date',
    # 'reform_wet_area_date',
    # 'reform_interior_date',
    # 'post1',
    # 'addr1_1',
    # 'bus_time1',
    # 'walk_distance1',
    # 'bus_time2',
    # 'walk_distance2',
    # 'house_kanrinin',
    # 'madori_number_all',
    # 'money_rimawari_now',
    # 'parking_distance',
    # 'school_ele_distance',
    # 'school_jun_distance',
    # 'convenience_distance',
    # 'super_distance',
    # 'hospital_distance',
    # 'park_distance',
    # 'drugstore_distance',
    # 'bank_distance',
    # 'building_type',
    # 'building_age',
    # 'years_since_renovation',
    'addr1+2',
    # 'tag_110101',
    # 'tag_110102',
    # 'tag_110201',
    # 'tag_110202',
    # 'tag_110301',
    # 'tag_110302',
    # 'tag_110401',
    # 'tag_110402',
    # 'tag_110501',
    # 'tag_110502',
    # 'tag_110503',
    # 'tag_110601',
    # 'tag_110602',
    # 'tag_110603',
    # 'tag_110701',
    # 'tag_110702',
    # 'tag_110801',
    # 'tag_110802',
    # 'tag_110901',
    # 'tag_110902',
    # 'tag_110903',
    # 'tag_111001',
    # 'tag_111002',
    # 'tag_113501',
    # 'tag_120501',
    # 'tag_120601',
    # 'tag_120801',
    # 'tag_123201',
    # 'tag_193501',
    # 'tag_210101',
    # 'tag_210102',
    # 'tag_210199',
    # 'tag_210201',
    # 'tag_210202',
    # 'tag_210299',
    # 'tag_210301',
    # 'tag_210302',
    # 'tag_210303',
    # 'tag_210399',
    # 'tag_210401',
    # 'tag_220101',
    # 'tag_220102',
    # 'tag_220103',
    # 'tag_220201',
    # 'tag_220202',
    # 'tag_220203',
    # 'tag_220301',
    # 'tag_220401',
    # 'tag_220501',
    # 'tag_220601',
    # 'tag_220701',
    # 'tag_220801',
    # 'tag_220901',
    # 'tag_223101',
    # 'tag_223201',
    # 'tag_223401',
    # 'tag_223501',
    # 'tag_223601',
    # 'tag_230101',
    # 'tag_230102',
    # 'tag_230103',
    # 'tag_230201',
    # 'tag_230202',
    # 'tag_230203',
    # 'tag_230204',
    # 'tag_230401',
    # 'tag_230501',
    # 'tag_230601',
    # 'tag_230701',
    # 'tag_230801',
    # 'tag_230901',
    # 'tag_233101',
    # 'tag_240101',
    # 'tag_240102',
    # 'tag_240103',
    # 'tag_240104',
    # 'tag_240201',
    # 'tag_250101',
    # 'tag_250201',
    # 'tag_250301',
    # 'tag_253301',
    # 'tag_253401',
    # 'tag_253501',
    # 'tag_253601',
    # 'tag_253701',
    # 'tag_260101',
    # 'tag_260201',
    # 'tag_260301',
    # 'tag_260401',
    # 'tag_260501',
    # 'tag_260503',
    # 'tag_263101',
    # 'tag_263201',
    # 'tag_283401',
    # 'tag_290101',
    # 'tag_290201',
    # 'tag_290301',
    # 'tag_290401',
    # 'tag_290501',
    # 'tag_290601',
    # 'tag_290701',
    # 'tag_290801',
    # 'tag_290901',
    # 'tag_290902',
    # 'tag_293101',
    # 'tag_293301',
    # 'tag_293601',
    # 'tag_293801',
    # 'tag_294201',
    # 'tag_294301',
    # 'tag_310101',
    # 'tag_310201',
    # 'tag_310501',
    # 'tag_320101',
    # 'tag_320201',
    # 'tag_320401',
    # 'tag_320501',
    # 'tag_320901',
    # 'tag_321001',
    # 'tag_321101',
    # 'tag_330101',
    # 'tag_330501',
    # 'tag_330601',
    # 'tag_330701',
    # 'tag_330801',
    # 'tag_331001',
    # 'tag_334001',
    # 'tag_334101',
    # 'tag_334201',
    # 'tag_334801',
    # 'tag_335001',
    # 'tag_335101',
    # 'tag_335201',
    # 'tag_335301',
    # 'tag_335401',
    # 'tag_335501',
    # 'tag_335601',
    # 'tag_335701',
    # 'tag_335901',
    # 'tag_335902',
    # 'tag_336001',
    # 'tag_336101',
    # 'tag_336201',
    # 'tag_336301',
    # 'tag_336401',
    # 'tag_336501',
    # 'tag_340101',
    # 'tag_340102',
    # 'tag_340201',
    # 'tag_340301',
    # 'tag_340401',
    # 'tag_350201'
      ]
  "CATEGORICAL_COLS":
   [
  #  "building_structure", 
  #  "management_form", 
   "floor_plan_code", 
  #  "house_kanrinin", 
  #  "land_youto", 
  #  "building_type",
   "addr1+2"
   ]

# LightGBM のパラメータ設定
MODEL_PARAMS:
    "objective": "huber"
    "metric": "None"     # ← fevalでMAPEを見るならこれでOK
    "alpha": 0.8
    'boosting_type': 'gbdt'
    "min_data_in_leaf": 50
    "learning_rate": 0.05
    "num_leaves": 64
    "max_depth": -1
    "feature_fraction": 0.8
    "bagging_fraction": 0.8
    "bagging_freq": 1
    "verbosity": -1